import { listCollection, requireFirestoreEnv } from '../lib/firestore.js';
import { requireStaffSession } from '../lib/staff-auth.js';

function clean(value) { return String(value ?? '').trim(); }
function lower(value) { return clean(value).toLowerCase(); }
function amount(value) { const number = Number(String(value ?? '0').replace(/,/g, '')); return Number.isFinite(number) ? number : 0; }
function money(value) { return `NGN ${amount(value).toLocaleString('en-NG', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }
function ascii(value) { return clean(value).replace(/[^\x20-\x7e]/g, ' '); }
function pdfEscape(value) { return ascii(value).replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)'); }

function payslipPdf(item) {
  const lines = [
    ['STAFF PAYSLIP', 16],
    [`Payroll month: ${ascii(item.Month)}`, 10],
    ['', 6],
    [`Staff name: ${ascii(item.DisplayName)}`, 10],
    [`Employee ID: ${ascii(item.EmployeeId)}`, 10],
    [`Department: ${ascii(item.Department)}`, 10],
    [`Position: ${ascii(item.Position)}`, 10],
    [`Bank: ${ascii(item.BankName)}  Account: ${ascii(item.AccountNumber)}`, 10],
    ['', 6], ['EARNINGS', 12],
    [`Basic salary: ${money(item.BasicSalary)}`, 10],
    ...(item.Allowances || []).map((row) => [`${ascii(row.Name)}: ${money(row.Amount)}`, 10]),
    [`Gross pay: ${money(item.GrossPay)}`, 11],
    ['', 6], ['DEDUCTIONS', 12],
    [`Pension: ${money(item.PensionAmount)}`, 10],
    [`Tax: ${money(item.TaxAmount)}`, 10],
    ...(item.OtherDeductions || []).map((row) => [`${ascii(row.Name)}: ${money(row.Amount)}`, 10]),
    [`Total deductions: ${money(item.TotalDeductions)}`, 11],
    ['', 6], [`NET PAY: ${money(item.NetPay)}`, 14],
    [`Payment status: ${ascii(item.PaymentStatus)} | Paid: ${money(item.PaidAmount)} | Outstanding: ${money(item.OutstandingAmount)}`, 9],
    ['', 6], ['Computer-generated by the Integrated School Management Suite.', 8]
  ];
  let y = 795;
  const commands = lines.map(([text, size]) => {
    const command = `BT /F1 ${size} Tf 50 ${y} Td (${pdfEscape(text)}) Tj ET`;
    y -= text ? Math.max(15, size + 5) : 9;
    return command;
  }).join('\n');
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    `<< /Length ${commands.length} >>\nstream\n${commands}\nendstream`
  ];
  let output = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach((object, index) => { offsets.push(output.length); output += `${index + 1} 0 obj\n${object}\nendobj\n`; });
  const xref = output.length;
  output += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.slice(1).forEach((offset) => { output += `${String(offset).padStart(10, '0')} 00000 n \n`; });
  output += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return new TextEncoder().encode(output);
}

export async function onRequestGet(context) {
  try {
    const { request, env } = context;
    requireFirestoreEnv(env);
    const user = await requireStaffSession(env, request);
    const url = new URL(request.url);
    const [items, runs] = await Promise.all([listCollection(env, 'payrollItems'), listCollection(env, 'payrollRuns')]);
    const visibleRuns = new Set(runs.filter((row) => ['posted', 'part paid', 'paid'].includes(lower(row.Status))).map((row) => lower(row.RunId)));
    const ownItems = items.filter((row) => lower(row.Username) === lower(user.username) && visibleRuns.has(lower(row.RunId)))
      .sort((a, b) => clean(b.Month).localeCompare(clean(a.Month)));
    const itemId = clean(url.searchParams.get('itemId'));
    if (lower(url.searchParams.get('action')) === 'payslip') {
      const item = ownItems.find((row) => clean(row.ItemId) === itemId || clean(row.__id) === itemId);
      if (!item) return Response.json({ ok: false, message: 'Payslip was not found for this staff account.' }, { status: 404 });
      return new Response(payslipPdf(item), { headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="Payslip_${ascii(item.Month)}_${ascii(item.EmployeeId)}.pdf"`,
        'Cache-Control': 'private, no-store', 'X-Content-Type-Options': 'nosniff'
      } });
    }
    return Response.json({ ok: true, message: 'Your payroll history was loaded.', items: ownItems.map((item) => ({
      ItemId: item.ItemId, RunId: item.RunId, Month: item.Month, DisplayName: item.DisplayName, Department: item.Department,
      Position: item.Position, BasicSalary: item.BasicSalary, AllowanceTotal: item.AllowanceTotal, GrossPay: item.GrossPay,
      TotalDeductions: item.TotalDeductions, NetPay: item.NetPay, PaidAmount: item.PaidAmount,
      OutstandingAmount: item.OutstandingAmount, PaymentStatus: item.PaymentStatus
    })) }, { headers: { 'Cache-Control': 'private, no-store' } });
  } catch (error) {
    return Response.json({ ok: false, message: clean(error && error.message ? error.message : error) }, { status: error.status || 500 });
  }
}
